@layout('home/application')

@section('content')<div class="container-extend grey" id="join">
  <div class="container">
    <h1>Join our team!</h1>    <p>There are 3 ways you can join UofT Developers:        <table id="joinOptions"><tr><td><h5>Learner</h5></td><td class="explanation"> you join us as a learning member where you get updates about club's events, lectures, workshops, job postings etc.</td></tr> 		<tr><td><h5>Developer</h5></td><td class="explanation"> you will join our development teams and start working on real project. You need to complete a simple project in the corresponding platform found in the Resources page</td></tr> 		<tr><td><h5>Sponsor</h5></td><td class="explanation"> you join us as a sponsor to our events and seminars.</td></tr></table> 		 		</p>	<hr>
    <p>Sign up below to join our mailing list</p>    <?php echo Form::open('joinus/joinus'); ?>    <table id="joinus">    	<tr><td><label>Name: </label></td>      <td><input type="text" placeholder="Name" name="name" required></td><td></td><td></td></tr>                <tr><td><label>Email: </label></td>      <td><input type="text" placeholder="Email" name="email" required></td>            <td><label>Programming Languages (if any)</label></td>      <td><textarea placeholder="Programming languages" name="language"></textarea></td>      </tr>      <tr><td><label>Year of Study: </label></td>      <td><select name="year" required>      <option value="1">First year</option>      <option value="2">Second year</option>      <option value="3">Third year</option>      <option value="4">Forth year or more</option>      </select></td>                  <td><label>Development Platforms (if any)</label></td>      <td><textarea placeholder="Development Platforms" name="platform"></textarea></td>      </tr>            <tr><td><label>Field of Study: </label></td>      <td><input type="text" max-length=30 placeholder="Major in" name="major" required></td>            <td><label>Additional Info: </label></td>      <td><textarea placeholder="About me" name="about"></textarea></td>      </tr>      
      <!--<tr><td><label>Student Number: </label></td>      <td><input type="text" placeholder="Student Number" name="number"></td><td></td><td></td></tr>-->      <tr><td><label>Team(s) of Interest: </label></td>      <td><input class="checkbox" type="checkbox" name="team1" value="Web">Web      <input class="checkbox" type="checkbox" name="team2" value="Android">Android      <input class="checkbox" type="checkbox" name="team3" value="iOS">iOS      <input class="checkbox" type="checkbox" name="team4" value="Design">Design      </td><td></td><td></td></tr>            <tr><td><label>Join us as a:</label></td>      <td><input class="radiobox" type="radio" name="joinas" value="learner" checked>Learner      <input class="radiobox" type="radio" name="joinas" value="developer">Developer      <input class="radiobox" type="radio" name="joinas" value="sponsor">Sponsor</td><td></td><td></td></tr>          						<tr><td colspan="4" style="text-align: center;"><?php echo Form::submit('Join Us', array('class' => 'btn btn-primary'));?></td></tr>    </table>    <?php echo Form::close(); ?>
  </div>
</div>
@endsection